### ISSUE TITLE
Doesn't work on Defold 1.4.6

### ISSUE THREAD

**Issue by sergeysinyavsky** [indiesoftby/defold-liveupdate-reszip#5]
When building a build on Defold version 1.4.6, the download does not end and an error occur

![image](https://github.com/indiesoftby/defold-liveupdate-reszip/assets/12486956/449a34ec-12d3-475c-9587-f2a0aeae0550)
![image](https://github.com/indiesoftby/defold-liveupdate-reszip/assets/12486956/741c07ef-020c-409d-aec8-cc81fd8f5de8)

Everything works on Defold version 1.4.5.

**Comment by aglitchman** [comment]
I'll take a look! Thanks!

**Comment by aglitchman** [comment]
It looks like a bug in the engine. I made a pull request to fit the bug.

@sergeysinyavsky It seems that you'll have to wait for Defold 1.4.7.

**Comment by sergeysinyavsky** [comment]
@aglitchman Thank you for checking!

**Comment by aglitchman** [comment]
Fixed in the engine; The asset works well in 1.4.7 ALPHA - https://github.com/defold/defold/issues/7688

Closed.
