### ISSUE TITLE
zip file loaded twice. Preload called after main.collection

### ISSUE THREAD

**Issue by d954mas** [indiesoftby/defold-liveupdate-reszip#6]
**Describe the bug**
liveupdate zip file loaded twice. If try load this file from main.collection
![2023-08-27_17-40-02](https://github.com/indiesoftby/defold-liveupdate-reszip/assets/2655263/2b471166-f988-4933-b8d5-575eb297529e)

preload called after call from script file.

https://github.com/indiesoftby/defold-liveupdate-reszip/assets/2655263/8e12d457-089e-40a1-8f1b-8b49b43e5af7

**To Reproduce**
1. add preload
2. start load zip in main.collection

**Expected behavior**
Preload always called first

**Comment by aglitchman** [comment]
Absolutely a good point!

In our projects, resource loading doesn't start in the first frame, so I've never experienced this problem.

**Comment by aglitchman** [comment]
Thank you! 🙌🏻
